# Generated by Django 5.0.6 on 2024-07-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "Category_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "Category",
            },
        ),
    ]
