# Generated by Django 5.0.6 on 2024-07-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Company_Name", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Recruiter",
            },
        ),
    ]
