# Generated by Django 5.0.6 on 2024-07-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seeker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UserName", models.CharField(max_length=40)),
                ("Email", models.EmailField(max_length=50)),
                ("PhNo", models.BigIntegerField()),
                ("Password", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "Seeker",
            },
        ),
    ]
