# Generated by Django 5.0.6 on 2024-07-26 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Admin", "0001_initial"),
        ("User", "0002_seeker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CompanyName", models.CharField(max_length=50)),
                ("Job_Title", models.CharField(max_length=50)),
                ("Description", models.CharField(max_length=100)),
                ("Experience", models.IntegerField(default=0)),
                ("Salary", models.FloatField(default=10000)),
                ("Location", models.CharField(max_length=50)),
                ("Skills", models.CharField(max_length=100)),
                ("Start_date", models.DateField()),
                ("End_date", models.DateField()),
                (
                    "category_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admin.category"
                    ),
                ),
            ],
            options={
                "db_table": "Job",
            },
        ),
    ]
