# Generated by Django 5.0.6 on 2024-07-26 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=20)),
                ("Last_Name", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=50)),
                ("PhNo", models.BigIntegerField()),
                ("Resume", models.FileField(upload_to="resumes")),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.job"
                    ),
                ),
            ],
            options={
                "db_table": "Apply",
            },
        ),
    ]
