# Generated by Django 5.0.6 on 2024-07-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image_url",
            field=models.ImageField(default="abc.jpg", upload_to="images"),
        ),
    ]
