# Generated by Django 5.0.6 on 2024-07-26 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0005_job_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="Description",
            new_name="Responsibility",
        ),
    ]
