# Generated by Django 5.0.6 on 2024-07-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0007_alter_job_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image_url",
            field=models.ImageField(default="abc.jpg", upload_to="images"),
        ),
    ]
