# Generated by Django 5.0.6 on 2024-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0010_alter_job_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="user",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
