# Generated by Django 5.0.6 on 2024-07-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0011_apply_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "job_status",
                    models.CharField(
                        choices=[("fresh", "Fresh"), ("working", "Already Working")],
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=255)),
                ("highest_degree_obtained", models.CharField(max_length=100)),
                ("major_field_of_study", models.CharField(max_length=100)),
                ("institution_name", models.CharField(max_length=255)),
                ("graduation_year", models.IntegerField()),
                ("technical_skills", models.TextField()),
                ("soft_skills", models.TextField()),
                ("hobbies", models.TextField()),
                ("interests", models.TextField()),
                ("languages_spoken", models.TextField()),
            ],
        ),
    ]
