# Generated by Django 5.0.6 on 2024-07-30 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0012_userprofile"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="UserProfile",
        ),
    ]
