# Generated by Django 5.0.6 on 2024-07-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0013_alter_userprofile_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="job_status",
            field=models.CharField(
                choices=[("fresher", "Fresher"), ("working", "Working")], max_length=20
            ),
        ),
    ]
