# Generated by Django 5.0.6 on 2024-07-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0014_alter_userprofile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
