# Generated by Django 5.0.6 on 2024-08-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0015_userprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Saved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("saved_on", models.DateTimeField(auto_now_add=True)),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.job"
                    ),
                ),
            ],
            options={
                "db_table": "Saved",
            },
        ),
    ]
