# Generated by Django 5.0.6 on 2024-08-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0016_saved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="job_status",
            field=models.CharField(max_length=20),
        ),
    ]
