# Generated by Django 5.0.6 on 2024-08-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0017_alter_userprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=50),
        ),
    ]
